### ISSUE TITLE
about 680M

### ISSUE THREAD

**Issue by OpenNEONE** [NootInc/NootedRed#149] opened 2023-08-16 15:39 UTC
We are keen to know when igpu's with 6000 series processors and above will be supported for mobile, such as the readon 680M, after all they have been on the market for a long, long time. Looking forward to getting your reply, thanks!

**Comment by ChefKissInc** [comment] 2023-08-16 15:40
Duplicate of #92

**Closed by ChefKissInc** 2023-08-16 15:40 UTC

**Comment by ChefKissInc** [comment] 2023-08-16 15:57
NRed's just me
