### ISSUE TITLE
AGDCC Unauthorized client 'PerfPowerService' AMDRadeonX6000_AmdGpuWrangler Catalina

### ISSUE THREAD

**Issue by hhk02** [NootInc/NootedRed#135] opened 2023-07-20 18:05 UTC
**To Reproduce**
1. Install Catalina ( NootedRed works in the installation progress)
2. After finish the install appears the Next line:
AGDCC Unauthorized client 'PerfPowerService' AMDRadeonX6000_AmdGpuWrangler
and stuck there.

**Screenshots**
![IMG_20230720_200347.jpg](https://github.com/NootInc/NootedRed/assets/80901734/da557059-cea9-4f0b-be38-4c1ec77c7ff1)

**System Information:**
 - macOS Version: Catalina
AMD Ryzen 7 3570H 
AMD Radeon 10 Vega 
SMBIOS used: MacBookPro16,3

i tested with iMacPro1,1 and appears a different error.

**Comment by hi-august** [comment] 2023-07-25 05:24
same issue, same efi works on monterey

**Comment by ChefKissInc** [comment] 2023-07-25 09:15
~~How about actually helping us find the issue rather than complaining and making new issues? Do you think we don’t test and know the problems of our experimental branches? Why would we keep the PRs drafted if we thought they were perfectly functional?~~

Duplicate of #134

**Closed by ChefKissInc** 2023-07-25 09:15 UTC
