### ISSUE TITLE
Hardware Acceleration Problem

### ISSUE THREAD

**Issue by Zahid1734** [NootInc/NootedRed#153] opened 2023-08-23 13:27 UTC
**Describe the bug**
While testing for hardware acceleration using the VDADecoderChecker
" An error was returned by the decoder layer. This may happen for example because of bitstream/data errors during a decode operation. This error may also be returned from VDADecoderCreate when hardware decoder resources are available on the system but currently in use by another process. VDADecoderCreate failed. err: -12473 "

**Expected behavior**
Hardware acceleration is fully supported

**System Information:**
 - macOS Version: Ventura 13.5
 - CPU: [e.g. AMD Ryzen 5 5600G]
 MB: Asus prime A520M-k

**Comment by ChefKissInc** [comment] 2023-08-23 13:28
Duplicate of #28

**Closed by ChefKissInc** 2023-08-23 13:28 UTC
Labels: Duplicate

**Comment by Kanepan** [comment] 2023-08-25 01:21
Can this be fixed? Looking forward to solving this problem, thank you
