### ISSUE TITLE
Black screen during initial system setup

### ISSUE THREAD

**Issue by lev666** [NootInc/NootedRed#102] opened 2023-06-21 14:37 UTC
**System Information:**
 - macOS Version: Latest Monterey/BigSur
 - CPU: ryzen 7 5800h with vega 8

**Additional context**
Good afternoon. I'm trying to boot with this kext on vega 8, but no matter how hard I try to change the config, the result is always the same - a black screen. And as I understand it, the system installer loads (because when the laptop lid is closed, it goes into sleep and quietly exits when the lid is opened), but the screen is black all the time, and after waking up, the screen backlight does not light up at all. Below I will attach a video of the last lines of loading and my efi

Kext used the newest version
[OC.zip](https://github.com/NootInc/NootedRed/files/11818843/OC.zip)

https://github.com/NootInc/NootedRed/assets/63856055/a602a075-06a9-4083-96e3-51e8d49a07af

**Comment by ChefKissInc** [comment] 2023-06-21 14:38
@lev666 If you followed the SMBIOS advice as statement in the README, then it’s the known (e)DP issue

**Comment by lev666** [comment] 2023-06-21 14:42
> @lev666 If you followed the SMBIOS advice as statement in the README, then it’s the known (e)DP issue

But if I understand correctly, then there is no solution to this problem yet?

**Comment by ChefKissInc** [comment] 2023-06-21 14:44
@lev666 A workaround that has been found, if you have no dGPU, is to boot with an external display plugged in.
Please do note that as soon as you boot another OS or your laptop completely discharges, it will break again

**Comment by lev666** [comment] 2023-06-21 14:47
> @lev666 A workaround that has been found, if you have no dGPU, is to boot with an external display plugged in. Please do note that as soon as you boot another OS or your laptop completely discharges, it will break again

I have a dGPU rtx 3060, but I disabled it via the ACPI table. Will your method work for me?

**Comment by lev666** [comment] 2023-06-21 14:49
> @lev666 No, because the external display is wired to the dGPU

So I thought. So far, there is no solution other than VESA mode?

**Comment by lev666** [comment] 2023-06-21 15:11
> did you try this for disable dgpu ? (fix with your device path)
> 
> ![Captura de ecrã 2023-06-21, às 16 06 43](https://user-images.githubusercontent.com/129546074/247598588-c976f99f-2510-4f0c-87ac-9185dd5f8779.png)

Thanks for the suggestion, but I don't think it would be of any use since I've already disabled rtx 3060, just via acpi directly

**Comment by lev666** [comment] 2023-06-22 11:02
> did you try this for disable dgpu ? (fix with your device path)
> i did try ssdt disables in the past and got no luck
> 
> ![Captura de ecrã 2023-06-21, às 16 06 43](https://github.com/NootInc/NootedRed/assets/129546074/c976f99f-2510-4f0c-87ac-9185dd5f8779)
> 

Well, if you think this can help me, then how can I find out the path to the device from under windows?

**Comment by lev666** [comment] 2023-06-23 15:29
> if you dont mind break sip try
> 
> ![Captura de ecrã 2023-06-23, às 16 12 45](https://github.com/NootInc/NootedRed/assets/129546074/87da4c4f-b46b-4fbe-897a-edd9472c8487)
> 

Changing SIP didn't help (but I didn't understand how it was supposed to help?)

**Comment by ChefKissInc** [comment] 2023-06-23 15:38
:/

**Comment by ChefKissInc** [comment] 2023-06-23 15:39
Closing and locking as a duplicate of #52

**Closed by ChefKissInc** 2023-06-23 15:39 UTC
Labels: Bug
