### ISSUE TITLE
Mendocino Support

### ISSUE THREAD

**Issue by meghan06** [NootInc/NootedRed#146] opened 2023-08-08 03:06 UTC
Mendocino is not mentioned in https://nootinc.github.io/nred#igpu-compatibility. Is there support for Mendocino in NR? 

TIA

**Comment by ChefKissInc** [comment] 2023-08-08 10:57
Mendocino is RDNA 2. Duplicate of #92

**Closed by ChefKissInc** 2023-08-08 10:57 UTC
Labels: Duplicate
