### ISSUE TITLE
Ryzen 3 3200G Vega 8 Big Sur Hackintosh Doesn't See Graphics

### ISSUE THREAD

**Issue by adwaitaplus** [NootInc/NootedRed#46] opened 2023-05-10 18:38 UTC
Even though I include the NootedRed plug-in in the EFI folder on the USB, it throws the black screen after the Verbose or Apple screen and does not fix it. I am trying to get image from A320M-A PRO motherboard with HDMI cable.

What is the problem?

I wrote a few hours ago to get help from you, but you locked the topic. I installed Hackintosh, but when booting, nootedred is active and a black screen comes after the verbose screen. With Nootedred disabled, the system boots without graphics acceleration.

**Comment by ChefKissInc** [comment] 2023-05-10 18:45
Duplicate of #45

**Closed by ChefKissInc** 2023-05-10 18:45 UTC
