### ISSUE TITLE
Black Screen after apple logo

### ISSUE THREAD

**Issue by mzl857** [NootInc/NootedRed#138] opened 2023-07-23 15:11 UTC
My laptop is Asus TUF Gaming A15（FA506QM)
 CPU : AMD RyzenR7 5800H
Display ：1920x1080 144hz
SMbios：MacBookPro16,3    Intel Core i5-8257U @ 1.40 GHz
OS : Mac os 11
Problem：Black screen after apple logo. I had tried Macos 11-13 , but, it does not work on my device.

**Comment by ExtremeXT** [comment] 2023-07-23 15:57
@mzl857 Does it boot fine without NootedRed? Check if your backlight flickers when on the black screen, if so you need to remote into the laptop and disable HDR. Else, it's a duplicate of #52.

**Comment by mzl857** [comment] 2023-07-23 16:38
> @mzl857 Does it boot fine without NootedRed? Check if your backlight flickers when on the black screen, if so you need to remote into the laptop and disable HDR. Else, it's a duplicate of #52.

without nootedred it boot fine.I will try it tomorrow, thanks for your advice!

**Comment by mzl857** [comment] 2023-07-24 02:20
I had remote into my laptop,nootedred works well,but the overview I can not see my graphics![Screenshot_20230724_101642.jpg](https://github.com/NootInc/NootedRed/assets/79705615/5a189771-decb-4773-bbf3-105d5dbccd0e)
And The screen is always dark without flickering.

**Comment by mzl857** [comment] 2023-07-24 02:50
I had remote into my laptop,nootedred works well,I can see my video card in the system information.but I can not see my video card in the  overview and my remote tools usually crash.the resolution is not right(not 1920x1080),I tried to change it in the remote tools,but it does not work.The screen is always dark without flickering.So now should I use the solution in #52？
![Screenshot_20230724_104828.jpg](https://github.com/NootInc/NootedRed/assets/79705615/45a1df90-8cf7-4a78-9991-61cd8fcedc04)
![Screenshot_20230724_101642_edit_316490095036082.jpg](https://github.com/NootInc/NootedRed/assets/79705615/3ceb9b3c-51e4-4294-b33e-a80455336eda)
![Screenshot_20230724_101612_youqu.android.todesk_edit_316503534571496.jpg](https://github.com/NootInc/NootedRed/assets/79705615/3e11302c-579d-431e-8215-71636f66b1c2)

**Comment by mzl857** [comment] 2023-07-24 04:16
> @mzl857 Does it boot fine without NootedRed? Check if your backlight flickers when on the black screen, if so you need to remote into the laptop and disable HDR. Else, it's a duplicate of #52.

I had used dbugenhancer.kext and It sent me back these two links
1.https://0x0.st/HeVq.txt
2.https://0x0.st/HeVT.txt
I don not know what is that mean.
![IMG_20230724_121555.jpg](https://github.com/NootInc/NootedRed/assets/79705615/1eb9b376-982e-4083-9dcc-1bfaa77519ef)

**Closed** 2023-07-24 06:23 UTC
Labels: Bug

**Comment by ExtremeXT** [comment] 2023-07-24 07:58
Duplicate of #52
