### ISSUE TITLE
Boot Process is getting stuck at "Registered CoreAnalyticsHub functions with xnu."

### ISSUE THREAD

**Issue by DevFelixLiS** [NootInc/NootedRed#78] opened 2023-06-06 12:21 UTC
Made an hackintosh with the opencore guide, implemented NootedRed and started booting. 

System Information:
 - macOS Version: 12.6.6
 - CPU: Ryzen 7 5825U
 
https://files.nocx420.xyz/tqkfsBaJ.jpeg

**Comment by DevFelixLiS** [comment] 2023-06-06 12:22
Let me know if more informations are needed.

**Comment by DevFelixLiS** [comment] 2023-06-06 12:22
Reddit Post: https://www.reddit.com/r/hackintosh/comments/13wgswi/stuck_at_registered_coreanalyticshub_functions/

**Comment by ChefKissInc** [comment] 2023-06-06 12:23
Does it boot without NRed

**Comment by DevFelixLiS** [comment] 2023-06-06 12:31
Nope. 
Maybe not because there is no kext for graphics in it.

**Comment by ChefKissInc** [comment] 2023-06-06 12:32
macOS can boot with VESA graphics. As your set up cannot boot even with the kext disabled, the problem is not related to NRed. Closing this issue

**Closed by ChefKissInc** 2023-06-06 12:32 UTC
Labels: Bug
