### ISSUE TITLE
Freezing and Screen Tearing Issues with Hardware Acceleration Enabled in Edge Browser

### ISSUE THREAD

**Issue by Geekmemz** [NootInc/NootedRed#122] opened 2023-07-12 10:40 UTC
**Describe the bug** After enabling hardware acceleration in the Edge browser, the computer freezes when entering characters in the address bar or playing videos. The freeze manifests as the mouse being able to move, but all other graphical interfaces are not moving. In addition, there is screen tearing when playing videos. When frozen, moving the mouse over the Dock does not enlarge it, even though Dock scaling is enabled in macOS settings. **To Reproduce** Steps to reproduce the behavior: 1. Enable hardware acceleration in the Edge browser 2. Enter characters in the address bar or play videos 3. Observe freezing and screen tearing 4. When frozen, move the mouse over the Dock and observe that it does not enlarge **Expected behavior** I expect the developer to fix this issue as soon as possible. **System Information:** - macOS Version: macOS 12.5 - CPU: AMD Ryzen 7 5700U **Additional context** The startup parameter nredvcn was added and the OC version is 092.
![IMG_20230712_182752](https://github.com/NootInc/NootedRed/assets/97420795/24181c10-9d6d-4a06-a387-a662896d4350)
![IMG_20230712_182752](https://github.com/NootInc/NootedRed/assets/97420795/3ceb1289-fb6e-4a56-a54c-a13f734d7286)
![Uploading IMG_20230712_182746.jpg…]()

**Comment by Geekmemz** [comment] 2023-07-12 10:41
![IMG_20230712_182746](https://github.com/NootInc/NootedRed/assets/97420795/ff148d8f-2513-4a5c-b1e2-84fac075209c)
![IMG_20230712_182629](https://github.com/NootInc/NootedRed/assets/97420795/93be7ebf-fb38-4e0c-a800-7b40cff599c2)
![IMG_20230712_182746](https://github.com/NootInc/NootedRed/assets/97420795/e16f5673-82e9-4b5f-96e6-52664b6b0559)
![Uploading IMG_20230712_182615.jpg…]()

**Comment by KlavierGayming** [comment] 2023-07-12 12:05
i most likely am not the one to be replying but it is known that chromium based browsers and some other things dont work properly

**Comment by Geekmemz** [comment] 2023-07-12 13:01
> 

So I submitted this issue, hoping that the developer will solve the problem with the application based on the Chromium kernel as soon as possible.

**Comment by KlavierGayming** [comment] 2023-07-12 13:10
You can disable GPU rasterisation as a workaround for now iirc. Sorry I didn't mention this in my first comment. (or just use safari or firefox)

**Comment by ChefKissInc** [comment] 2023-07-12 13:11
It's in the NRed FAQ

**Comment by truongvantuan** [comment] 2023-07-12 14:32
Could you share us the FAQ link?

**Comment by ChefKissInc** [comment] 2023-07-12 14:33
@truongvantuan It’s literally set as the repo’s homepage and is in the README

**Comment by Geekmemz** [comment] 2023-07-12 17:34
I noticed that this issue has been listed as a known issue, but it has not been resolved yet. This issue is very important to me and I hope it can be resolved as soon as possible. Can you tell me about the progress of resolving this issue? Thank you.

**Comment by AlphaNecron** [comment] 2023-07-12 18:53
Be patient, it's being fixed, not only you waiting for fixes but also everyone does.

**Comment by ChitoKim** [comment] 2023-07-15 12:24
Maybe install a lower version of your browser. In my case chromium downgrade just worked

**Comment by ChefKissInc** [comment] 2023-07-15 16:14
Duplicate of #13

**Closed by ChefKissInc** 2023-07-15 16:14 UTC
Labels: Bug
