### ISSUE TITLE
Chromium-based browsers issue

### ISSUE THREAD

**Issue by ruslanshchur** [NootInc/NootedRed#48] opened 2023-05-14 08:18 UTC
Hi! When I trying to run any Chromium-based browser on macOS 11.7.5 Big Sur with NootedRed, I am getting kernel panic (for me it is not showing, so, it feels like that macOS is hanged up), so, can this serious issue be fixed in future releases of NootedRed? P.S. I used it from master branch

System Information:
macOS 11.7.5
AMD Ryzen 5 3500U
AMD Radeon RX Vega 8

**Comment by ChefKissInc** [comment] 2023-05-14 08:44
@ruslanshchur Fetch the `.gpuRestart` files from `/Library/Logs/DiagnosticReports`

**Comment by ChefKissInc** [comment] 2023-05-14 12:05
(Also, Electron apps work fine on my device, and Electron does use Chromium)

**Comment by ChefKissInc** [comment] 2023-05-14 14:02
@jalavoui I still need the gpu crash logs

**Comment by ChefKissInc** [comment] 2023-05-14 14:45
Duplicate of #13. This issue falls under the same category

**Closed by ChefKissInc** 2023-05-14 14:45 UTC
Labels: Bug
